### PR TITLE
set ENABLE_BITCODE=No to be compatible wite xcode8.3

### PR DESCRIPTION
**Pull request by lina1**

### CODE REVIEW

**Comment by lina1** [comment]
After xcode upgrade to 8.3, the ENABLE_BITCODE  will be set to Yes by default, then the monkey test cannot run on real device, so ENABLE_BITCODE should be set to No explicitly  in SwiftMonkey.

**Comment by lasomethingsomething** [comment]
@lina1, thank you for the PR. @DagAgren, can you please take a look and get back to this potential contributor?

**Comment by wojciechczerski** [comment]
👍

**Comment by m619** [comment]
👍

**Comment by wojciechczerski** [comment]
@DagAgren @LappleApple Could you please have a look / merge this PR?

**Comment by DagAgren** [comment]
If you have tested that it works, feel free to merge it yourself. Do you have access to do it?

**Comment by wojciechczerski** [comment]
@DagAgren I do not have the permission to do so, but I did test the change.

**Comment by lasomethingsomething** [comment]
@wojciechczerski: I've made you an admin

**Pull request merged**
